export const COURSE_NOTE_TITLE = "Ifeoma_lesson updated.docx";

export const COURSE_SCOPE_TOPICS = [
  "conservation of natural resources",
  "meaning of conservation",
  "importance of conservation",
  "soil conservation methods",
  "water conservation methods",
  "sustainable use",
  "protection and preservation",
  "efficient utilization",
  "restoration and renewal",
  "afforestation",
  "reforestation",
  "contour ploughing",
  "terracing",
  "crop rotation",
  "cover cropping",
  "green manure",
  "mulching",
  "strip cropping",
  "conservation tillage",
  "gully control",
  "controlled grazing",
  "rainwater harvesting",
  "drip irrigation",
  "sprinkler irrigation",
  "greywater recycling",
  "groundwater conservation",
  "forest conservation",
  "wildlife conservation",
  "conservation symbols",
  "conservation slogans",
  "protected areas",
  "bush burning",
  "overgrazing",
  "social forestry",
  "wildlife corridors",
  "captive breeding",
  "habitat conservation",
  "recycling symbol",
  "tree symbol",
  "panda symbol",
  "earth symbol",
  "globe symbol",
  "water drop symbol",
  "green leaf symbol",
  "pests and diseases",
  "types of pests",
  "types of plant diseases",
  "pest control methods",
  "disease control methods",
  "benefits and drawbacks of control methods",
  "insect pests",
  "mite pests",
  "nematode pests",
  "rodent pests",
  "bird pests",
  "mollusk pests",
  "weed pests",
  "microbial pests",
  "aphids",
  "grasshoppers",
  "caterpillars",
  "whiteflies",
  "weevils",
  "spider mites",
  "root-knot nematodes",
  "rats",
  "mice",
  "snails",
  "slugs",
  "striga",
  "water hyacinth",
  "fungal diseases",
  "bacterial diseases",
  "viral diseases",
  "powdery mildew",
  "rust",
  "leaf spot",
  "bacterial blight",
  "bacterial wilt",
  "tobacco mosaic virus",
  "cassava mosaic disease",
  "maize streak virus",
  "chemical control",
  "biological control",
  "cultural control",
  "mechanical control",
  "physical control",
  "integrated pest",
  "integrated disease",
  "reproductive system in birds and mammals",
  "reproduction in birds",
  "reproduction in mammals",
  "comparison between reproduction in birds and mammals",
  "roles of male and female reproductive organs in birds and mammals",
  "humans",
  "dogs",
  "lions",
  "elephants",
  "hen",
  "pigeon",
  "eagle",
  "sexual reproduction",
  "internal fertilization",
  "oviparous",
  "viviparous",
  "incubation",
  "gestation",
  "testes",
  "vas deferens",
  "cloaca",
  "phallus",
  "ovary",
  "oviduct",
  "infundibulum",
  "magnum",
  "isthmus",
  "shell gland",
  "vagina",
  "epididymis",
  "seminal vesicles",
  "prostate gland",
  "cowper",
  "urethra",
  "penis",
  "ovaries",
  "fallopian tubes",
  "uterus",
  "endometrium",
  "cervix",
  "mammary glands",
  "drawing and labelling reproductive systems of birds and mammals",
  "fertilization in birds and mammals",
  "embryonic development in birds and mammals",
  "parental care in birds and mammals",
  "stages of embryonic development",
  "zygote",
  "gamete",
  "sperm",
  "ovum",
  "egg",
  "albumen",
  "embryo",
  "blastocyst",
  "placenta",
  "umbilical cord",
  "fetus",
  "hatching"
];

export const COURSE_REFUSAL =
  "I am designed to teach only the Biology lessons provided in this course. Please ask questions related to conservation of natural resources, pest and disease control, or reproduction in birds and mammals.";

const COURSE_KEYWORDS = [
  "conservation",
  "natural",
  "resources",
  "soil",
  "water",
  "forest",
  "wildlife",
  "symbol",
  "slogan",
  "afforestation",
  "reforestation",
  "ploughing",
  "terracing",
  "mulching",
  "irrigation",
  "rainwater",
  "pest",
  "pests",
  "disease",
  "diseases",
  "plant",
  "plants",
  "fungal",
  "bacterial",
  "viral",
  "nematode",
  "rodent",
  "insect",
  "aphid",
  "weevil",
  "control",
  "chemical",
  "biological",
  "cultural",
  "mechanical",
  "ipm",
  "reproduction",
  "reproductive",
  "bird",
  "birds",
  "mammal",
  "mammals",
  "human",
  "humans",
  "dog",
  "dogs",
  "lion",
  "lions",
  "elephant",
  "elephants",
  "hen",
  "pigeon",
  "eagle",
  "fertilization",
  "fertilisation",
  "embryonic",
  "embryo",
  "zygote",
  "gamete",
  "sperm",
  "ovum",
  "egg",
  "incubation",
  "hatching",
  "uterus",
  "placenta",
  "oviduct",
  "infundibulum",
  "cloaca",
  "testes",
  "ovary",
  "parental",
  "care"
];

export function isApprovedCourseTopic(value: string) {
  const normalized = value.toLowerCase();
  if (COURSE_SCOPE_TOPICS.some((topic) => normalized.includes(topic))) return true;

  const words = normalized.match(/[a-z]+/g) ?? [];
  const keywordHits = new Set(words.filter((word) => COURSE_KEYWORDS.includes(word)));
  return keywordHits.size > 0;
}

export const COURSE_SCOPE_SUMMARY = COURSE_SCOPE_TOPICS.map((topic) => `- ${topic}`).join("\n");
