export const LESSON_NOTE_CONTEXT = `
Source: Ifeoma_lesson updated.docx. Subject: Biology. Class: SSII.

LESSON ONE: Conservation of Natural Resources.
Specific objectives: explain the concept of conservation of natural resources; mention the importance of conserving natural resources; describe methods of conservation for soil; list methods of conservation for water.
Conservation of natural resources means the careful use, management, and protection of natural resources such as water, soil, forests, minerals, fossil fuels, wildlife, and biodiversity so they are available for present and future generations. Natural resources are limited and exhaustible if misused, so they must be used wisely and sustainably.
Key ideas: sustainable use; protection and preservation; efficient utilization; restoration and renewal; balancing development and environment.
Importance: sustainability for future generations; environmental protection; economic benefits; preservation of biodiversity; climate regulation; soil and water conservation; reduced dependency on non-renewable resources; improved quality of life.
Soil conservation methods: afforestation and reforestation; contour ploughing; terracing; crop rotation; cover cropping or green manure; mulching; strip cropping; conservation tillage or zero/minimum tillage; gully control; controlled grazing.
Water conservation methods: rainwater harvesting; efficient irrigation practices such as drip and sprinkler irrigation; reuse and recycling of water, including greywater and industrial recycling; protection of water sources; reducing water pollution; groundwater conservation; water-saving technologies at home; public awareness and education.

LESSON TWO: Forest Conservation, Wildlife Conservation, Conservation Symbols, and Conservation Slogans.
Specific objectives: describe methods of conservation for forests; describe methods of conservation for wildlife; identify and interpret conservation symbols and slogans.
Forest conservation methods: afforestation; reforestation; controlled and regulated cutting; prevention of bush burning; prevention of overgrazing; social forestry; establishment of protected areas; forest legislation and policies; public awareness and community participation.
Wildlife conservation methods: establishment of protected areas such as national parks, wildlife sanctuaries, and game reserves; legislation and enforcement of laws; captive breeding and rehabilitation; habitat conservation and restoration; prevention of over-exploitation; wildlife corridors; control of pollution and climate change; community participation and education.
Conservation symbols: recycling symbol with three arrows meaning reduce, reuse, recycle; tree symbol meaning protect forests and plant more trees; panda symbol meaning protection of endangered species and biodiversity; earth/globe symbol meaning protect the earth and conserve resources; water drop symbol meaning conserve water and prevent wastage; green leaf symbol meaning eco-friendliness and protecting plant life.
Conservation slogans: Reduce, Reuse, Recycle; Plant a tree, plant a life; Save water, save life; Forests are the lungs of the Earth; Conserve energy, preserve future; Protect wildlife, protect nature; Don't let our future dry up; Go green, breathe clean; Nature is priceless, conserve it.

LESSON THREE: Pests and Diseases.
Specific objectives: define pests and diseases; identify common types of pests and plant diseases; describe methods of pest control; explain methods of disease control; analyze benefits and drawbacks of control methods.
Pests are organisms such as insects, weeds, fungi, rodents, bacteria, or other animals considered harmful to humans, crops, livestock, property, or the environment because they cause damage, compete for resources, or transmit diseases.
A disease is an abnormal condition in a living organism that disrupts normal structure or function, usually caused by pathogens, environmental factors, or genetic disorders. In plants, diseases may be caused by fungi, bacteria, viruses, or unfavorable conditions, leading to reduced growth, poor yield, or death.
Types of plant diseases: fungal diseases such as powdery mildew, rust, leaf spot, damping-off, and late blight; bacterial diseases such as bacterial blight, bacterial wilt, fire blight, and soft rot; viral diseases such as tobacco mosaic virus, cassava mosaic disease, maize streak virus, and banana bunchy top virus; nematode diseases such as root-knot nematode disease, cyst nematode infection, and lesion nematodes; mycoplasma and phytoplasma diseases such as little leaf of brinjal, grassy shoot of sugarcane, and sandal spike disease; abiotic or non-infectious diseases such as nutrient deficiency, sunscald, frost injury, pollution damage, and salt stress.
Types of pests: insect pests such as aphids, grasshoppers, caterpillars, whiteflies, and weevils; mite pests such as spider mites and red mites; nematode pests such as root-knot nematodes and cyst nematodes; rodent pests such as rats and mice; bird pests such as sparrows and quelea birds; mollusk pests such as snails and slugs; weed pests such as striga and water hyacinth; microbial pests such as fungi, bacteria, and viruses.
Pest control methods: chemical control using pesticides, insecticides, herbicides, and rodenticides; biological control using natural predators or pathogens; cultural control such as crop rotation, weeding, and sanitation; mechanical control using traps, nets, manual removal, and barriers.
Disease control methods: chemical methods using fungicides, bactericides, and nematicides; cultural methods such as removing infected plants, proper spacing, sanitation, and good drainage; biological methods using resistant plant varieties or beneficial microbes; quarantine and legislation to restrict movement of infected plants and prevent disease spread.
Benefits of control methods: increased crop yield, improved food quality, and reduced economic losses. Drawbacks: environmental pollution, resistance, harm to non-target species, cost, need for training, slow effect for some methods, and labour intensity.
Integrated Pest/Disease Management combines cultural, biological, mechanical, and chemical methods and offers a balance of effectiveness, cost, and sustainability.

LESSON FOUR: Reproductive System in Birds and Mammals.
Specific objectives: describe reproductive systems of birds and mammals; differentiate reproductive processes in birds and mammals; identify roles of male and female reproductive organs in birds and mammals.
Reproduction in birds is the biological process by which birds produce offspring through sexual reproduction, internal fertilization, egg formation, incubation, and hatching. Features: sexual reproduction; internal fertilization; egg laying or oviparous reproduction; incubation; parental care.
Reproduction in mammals is the biological process by which new individuals are produced through sexual reproduction, internal fertilization, and development of the young inside the mother's body. Features: sexual reproduction; internal fertilization; mostly viviparous live birth except monotremes; gestation; parental care and feeding with milk from mammary glands.
Comparison: birds and mammals both reproduce sexually and have internal fertilization. Birds lay shelled eggs, embryos develop outside the mother's body inside eggs, embryos are nourished by yolk, and young hatch from eggs. Mammals mostly give birth to live young, embryos develop inside the uterus, embryos are nourished by the placenta except monotremes, and mothers feed young with milk.
Male bird organs: testes produce sperm and testosterone; vas deferens transports sperm; cloaca releases sperm during mating; phallus in some birds assists sperm transfer.
Female bird organs: ovary produces ova and female hormones; oviduct transports the egg and adds protective layers; infundibulum receives the ovulated egg and is the site of fertilization; magnum secretes albumen; isthmus adds shell membranes; uterus or shell gland adds hard shell; vagina helps in laying the egg; cloaca is the opening for egg-laying and excretion.
Male mammal organs: testes produce sperm and testosterone; epididymis stores and matures sperm; vas deferens transports sperm; seminal vesicles produce nutrient-rich semen; prostate gland helps sperm move and survive; Cowper's glands produce lubricating mucus; urethra is a passage for semen and urine; penis delivers sperm.
Female mammal organs: ovaries produce eggs and hormones; fallopian tubes transport eggs and are the site of fertilization; uterus supports implantation and embryo development; endometrium nourishes the embryo; cervix controls passage and protects the uterus; vagina receives sperm and is the birth canal; mammary glands produce milk.

LESSON SIX: Drawing and Labelling Reproductive Systems, Fertilization, Embryonic Development, and Parental Care in Birds and Mammals.
Specific objectives: draw and label reproductive systems of birds and mammals; explain fertilization, embryonic development, and parental care in birds and mammals; list stages involved in embryonic development.
Fertilization is the process by which a male gamete, the sperm cell, fuses with a female gamete, the egg or ovum, to form a zygote. Features: union of gametes; restoration of chromosome number; initiation of development.
Fertilization in birds: internal fertilization. During mating, male and female cloacae touch and sperm is transferred to the female reproductive tract. Fertilization occurs in the infundibulum of the oviduct shortly after ovulation. A zygote forms, travels down the oviduct, and receives albumen, membranes, and a hard shell. A fertilized egg is laid, incubated, and later hatches into a chick.
Fertilization in mammals: internal fertilization. During copulation, sperm is deposited in the vagina, travels through the cervix and uterus into the fallopian tube, and fuses with an ovum. The zygote divides as it moves to the uterus, implants in the uterine wall, and develops into an embryo.
Differences in fertilization: in birds, fertilization site is the infundibulum of the oviduct, development is external in an egg, and birth is by hatching. In mammals, fertilization site is the fallopian tube, development is internal in the uterus and nourished by the placenta, and birth is live birth except monotremes.
Embryonic development in birds: the fertilized egg grows and differentiates into a chick inside the egg outside the mother. The zygote moves down the oviduct, albumen, membranes, and shell are added, the egg is laid and incubated, the embryo uses nutrients from yolk, organs form, and the chick hatches.
Embryonic development in mammals: the zygote forms in the fallopian tube, divides into a blastocyst, implants in the uterine wall, receives oxygen and nutrients through the placenta and umbilical cord, cells differentiate into tissues and organs, and the embryo becomes a fetus until birth.
`;
