import type { Difficulty, Question } from "@/lib/types";

function mcq(id: string, topicSlug: string, prompt: string, options: string[], correctAnswer: string, explanation: string, difficulty: Difficulty): Question {
  return { id, topicSlug, prompt, options, correctAnswer, explanation, difficulty };
}

const l1 = "lesson-one-conservation-natural-resources";
const l2 = "lesson-two-forest-wildlife-conservation";
const l3 = "lesson-three-pests-diseases-control";
const l4 = "lesson-four-reproduction-birds-mammals";
const l6 = "lesson-six-fertilization-development-care";

export const starterQuestionBanks: Record<string, Question[]> = {
  [l1]: [
    mcq("l1-q1", l1, "What is conservation of natural resources?", ["Careful use, management, and protection of resources", "Wasting resources quickly", "Destroying resources for development", "Using only fossil fuels"], "Careful use, management, and protection of resources", "Conservation means using, managing, and protecting natural resources so they remain useful now and in the future.", "easy"),
    mcq("l1-q2", l1, "Which of these is a natural resource?", ["Soil", "Plastic chair", "Concrete block", "Exercise book"], "Soil", "Soil is supplied by nature and is listed as a natural resource.", "easy"),
    mcq("l1-q3", l1, "Why is conservation important?", ["It keeps resources available for present and future generations", "It makes resources disappear faster", "It stops all farming", "It increases pollution"], "It keeps resources available for present and future generations", "Conservation supports sustainability for people living now and those who will live later.", "easy"),
    mcq("l1-q4", l1, "Which method helps conserve soil by planting trees?", ["Afforestation", "Overgrazing", "Bush burning", "Water pollution"], "Afforestation", "Afforestation means planting trees, which helps protect soil from erosion.", "easy"),
    mcq("l1-q5", l1, "Which is a water conservation method?", ["Rainwater harvesting", "Gully erosion", "Deforestation", "Uncontrolled grazing"], "Rainwater harvesting", "Rainwater harvesting stores rainwater for later use and reduces waste.", "easy"),
    mcq("l1-q6", l1, "What does soil conservation mainly prevent?", ["Erosion and loss of fertility", "Egg hatching", "Animal migration", "Photosynthesis"], "Erosion and loss of fertility", "Soil conservation protects soil from being washed away and losing nutrients.", "medium"),
    mcq("l1-q7", l1, "What is crop rotation?", ["Growing different crops on the same land in sequence", "Burning crop residues every day", "Planting only one crop forever", "Removing all vegetation from soil"], "Growing different crops on the same land in sequence", "Crop rotation helps maintain soil fertility and can reduce pest and disease build-up.", "medium"),
    mcq("l1-q8", l1, "How does mulching conserve soil?", ["It covers the soil surface and reduces erosion", "It removes all soil organisms", "It increases water pollution", "It destroys plant roots"], "It covers the soil surface and reduces erosion", "Mulch protects the soil surface from direct rain, wind, and moisture loss.", "medium"),
    mcq("l1-q9", l1, "Which method is best for farming on slopes?", ["Terracing", "Overgrazing", "Open dumping", "Uncontrolled logging"], "Terracing", "Terracing makes step-like levels on slopes and slows water runoff.", "medium"),
    mcq("l1-q10", l1, "What is contour ploughing?", ["Ploughing along the natural contour lines of a slope", "Ploughing straight downhill", "Removing topsoil", "Digging random pits only"], "Ploughing along the natural contour lines of a slope", "Contour ploughing reduces runoff by following the shape of the land.", "medium"),
    mcq("l1-q11", l1, "Which practice can damage soil if not controlled?", ["Overgrazing", "Cover cropping", "Mulching", "Reforestation"], "Overgrazing", "Too many animals can remove plant cover, exposing soil to erosion.", "medium"),
    mcq("l1-q12", l1, "Which method uses plants to cover and protect soil?", ["Cover cropping", "Water pollution", "Quarrying", "Bush burning"], "Cover cropping", "Cover crops protect soil and can improve fertility.", "medium"),
    mcq("l1-q13", l1, "What is groundwater conservation concerned with?", ["Protecting and using underground water wisely", "Cutting all forest trees", "Destroying wildlife habitats", "Increasing soil erosion"], "Protecting and using underground water wisely", "Groundwater conservation helps keep underground water available and clean.", "medium"),
    mcq("l1-q14", l1, "Which household action conserves water?", ["Fixing leaking taps", "Leaving taps running", "Polluting streams", "Wasting stored rainwater"], "Fixing leaking taps", "Fixing leaks reduces unnecessary water loss.", "easy"),
    mcq("l1-q15", l1, "Why should water sources be protected?", ["To keep water clean and safe for use", "To increase disease spread", "To destroy aquatic life", "To waste water faster"], "To keep water clean and safe for use", "Protecting water sources reduces pollution and keeps water useful.", "medium"),
    mcq("l1-q16", l1, "Which pair belongs to Lesson One?", ["Soil conservation and water conservation", "Forest slogans and wildlife corridors", "Fertilization and parental care", "Pest symptoms and quarantine"], "Soil conservation and water conservation", "Lesson One focuses on conservation, including soil and water conservation methods.", "hard"),
    mcq("l1-q17", l1, "What does sustainable use mean?", ["Using resources carefully so they are not exhausted", "Using all resources at once", "Destroying resources before use", "Ignoring future needs"], "Using resources carefully so they are not exhausted", "Sustainable use balances present needs with future availability.", "hard"),
    mcq("l1-q18", l1, "Which method repairs serious channels formed by erosion?", ["Gully control", "Overgrazing", "Bush burning", "Pollution"], "Gully control", "Gully control prevents erosion channels from widening and damaging land.", "hard"),
    mcq("l1-q19", l1, "How does conservation improve quality of life?", ["It protects resources people need for health and livelihood", "It removes all useful resources", "It increases waste", "It stops clean water access"], "It protects resources people need for health and livelihood", "People depend on soil, water, forests, and other resources for survival and economic activities.", "hard"),
    mcq("l1-q20", l1, "Which option is not a soil conservation method?", ["Water pollution", "Mulching", "Terracing", "Crop rotation"], "Water pollution", "Water pollution damages resources; it is not a soil conservation method.", "hard")
  ],

  [l2]: [
    mcq("l2-q1", l2, "What is forest conservation?", ["Protection and responsible management of forests", "Cutting all trees", "Hunting all wild animals", "Wasting water"], "Protection and responsible management of forests", "Forest conservation keeps forests healthy and useful.", "easy"),
    mcq("l2-q2", l2, "What is wildlife conservation?", ["Protection of wild animals and their habitats", "Keeping only domestic animals", "Destroying game reserves", "Burning forests"], "Protection of wild animals and their habitats", "Wildlife conservation protects animals and the places where they live.", "easy"),
    mcq("l2-q3", l2, "Which is a forest conservation method?", ["Reforestation", "Poaching", "Overgrazing", "Bush burning"], "Reforestation", "Reforestation means replanting trees in depleted forests.", "easy"),
    mcq("l2-q4", l2, "What does afforestation mean?", ["Planting trees in areas where there were no forests", "Cutting trees without control", "Hunting animals illegally", "Polluting rivers"], "Planting trees in areas where there were no forests", "Afforestation creates tree cover and supports conservation.", "easy"),
    mcq("l2-q5", l2, "Why should bush burning be prevented?", ["It destroys forests and habitats", "It improves every habitat", "It protects all seedlings", "It increases wildlife safety"], "It destroys forests and habitats", "Bush burning can kill plants, animals, and soil organisms.", "easy"),
    mcq("l2-q6", l2, "Which area is set aside to protect wildlife?", ["Game reserve", "Open dumping site", "Shopping mall", "Quarry"], "Game reserve", "Game reserves and national parks protect wildlife and habitats.", "medium"),
    mcq("l2-q7", l2, "What is controlled logging?", ["Cutting trees responsibly and sustainably", "Cutting every tree at once", "Burning young forests", "Removing all wildlife"], "Cutting trees responsibly and sustainably", "Controlled logging reduces forest destruction by regulating tree cutting.", "medium"),
    mcq("l2-q8", l2, "Which conservation symbol suggests reduce, reuse, and recycle?", ["Recycling symbol", "Skull symbol", "Traffic light", "Thermometer"], "Recycling symbol", "The recycling symbol reminds people to reduce, reuse, and recycle materials.", "medium"),
    mcq("l2-q9", l2, "What does a water drop symbol usually promote?", ["Water conservation", "Poaching", "Deforestation", "Overgrazing"], "Water conservation", "A water drop symbol reminds people to save and protect water.", "medium"),
    mcq("l2-q10", l2, "What is the purpose of conservation slogans?", ["To encourage people to conserve resources", "To replace scientific names", "To identify mammal organs", "To spread plant diseases"], "To encourage people to conserve resources", "Slogans are short messages that promote conservation behavior.", "medium"),
    mcq("l2-q11", l2, "Which slogan promotes tree planting?", ["Plant a tree, plant a life", "Destroy forests today", "Waste water daily", "Poach wildlife now"], "Plant a tree, plant a life", "This slogan encourages tree planting and forest protection.", "medium"),
    mcq("l2-q12", l2, "Which method helps prevent illegal hunting?", ["Legislation and enforcement", "Poaching", "Uncontrolled hunting", "Habitat destruction"], "Legislation and enforcement", "Wildlife laws and enforcement reduce illegal hunting.", "medium"),
    mcq("l2-q13", l2, "What is habitat restoration?", ["Repairing damaged places where organisms live", "Destroying forest homes", "Draining every wetland", "Cutting all trees"], "Repairing damaged places where organisms live", "Restoration improves damaged habitats so wildlife can survive.", "medium"),
    mcq("l2-q14", l2, "Why are wildlife corridors useful?", ["They allow animals to move safely between habitats", "They trap animals for poachers", "They stop all animal movement", "They remove forests"], "They allow animals to move safely between habitats", "Corridors connect habitats and reduce isolation of wildlife populations.", "hard"),
    mcq("l2-q15", l2, "What is social forestry?", ["Community involvement in planting and managing trees", "Illegal timber trade", "Burning forest edges", "Removing tree seedlings"], "Community involvement in planting and managing trees", "Social forestry involves people and communities in forest conservation.", "hard"),
    mcq("l2-q16", l2, "Which symbol can represent care for the earth?", ["Earth or globe symbol", "Broken bottle", "Poison label", "Empty cage"], "Earth or globe symbol", "The earth or globe symbol represents environmental care and conservation.", "easy"),
    mcq("l2-q17", l2, "Which topic belongs to Lesson Two?", ["Conservation symbols and slogans", "Soil terracing only", "Mammalian uterus only", "Root-knot nematode only"], "Conservation symbols and slogans", "Lesson Two includes forest conservation, wildlife conservation, symbols, and slogans.", "hard"),
    mcq("l2-q18", l2, "What is captive breeding?", ["Breeding endangered animals under human care before release or protection", "Burning forest land", "Polluting habitats", "Cutting protected trees"], "Breeding endangered animals under human care before release or protection", "Captive breeding can help restore threatened wildlife populations.", "hard"),
    mcq("l2-q19", l2, "Why is public awareness important in conservation?", ["It teaches people how to protect resources", "It encourages careless use", "It promotes poaching", "It stops community action"], "It teaches people how to protect resources", "Awareness helps people understand and practice conservation.", "medium"),
    mcq("l2-q20", l2, "Which action harms forest conservation?", ["Prevention of bush burning", "Controlled cutting", "Reforestation", "Overgrazing"], "Overgrazing", "Overgrazing removes vegetation and can damage forests and soil.", "hard")
  ],

  [l3]: [
    mcq("l3-q1", l3, "What is a pest?", ["An organism that harms crops, livestock, property, or the environment", "A conservation slogan", "A reproductive organ", "A water-saving device"], "An organism that harms crops, livestock, property, or the environment", "Pests cause damage, compete for resources, or transmit diseases.", "easy"),
    mcq("l3-q2", l3, "Which is an insect pest?", ["Grasshopper", "Mango tree", "Water drop", "Placenta"], "Grasshopper", "Grasshoppers are examples of insect pests.", "easy"),
    mcq("l3-q3", l3, "Which is a rodent pest?", ["Rat", "Aphid", "Leaf spot", "Tree emblem"], "Rat", "Rats and mice are rodent pests.", "easy"),
    mcq("l3-q4", l3, "What is a plant disease?", ["An abnormal condition that disrupts normal plant growth or function", "A type of forest law", "A conservation slogan", "A mammary gland"], "An abnormal condition that disrupts normal plant growth or function", "Plant diseases affect normal plant structure or function.", "easy"),
    mcq("l3-q5", l3, "Which pathogen can cause plant disease?", ["Fungus", "Contour line", "Game reserve", "Recycling symbol"], "Fungus", "Fungi can cause plant diseases such as powdery mildew and rust.", "easy"),
    mcq("l3-q6", l3, "Which is a fungal disease example?", ["Powdery mildew", "Cassava mosaic disease", "Bacterial wilt", "Water conservation"], "Powdery mildew", "Powdery mildew is listed as a fungal disease.", "medium"),
    mcq("l3-q7", l3, "Which is a viral plant disease example?", ["Tobacco mosaic virus", "Soft rot", "Rust", "Root-knot nematode"], "Tobacco mosaic virus", "Tobacco mosaic virus is a viral disease.", "medium"),
    mcq("l3-q8", l3, "Which is a bacterial disease example?", ["Bacterial blight", "Rust", "Powdery mildew", "Cassava mosaic disease"], "Bacterial blight", "Bacterial blight is caused by bacteria.", "medium"),
    mcq("l3-q9", l3, "What is chemical control?", ["Use of approved pesticides or chemicals to control pests or diseases", "Using natural enemies only", "Hand-picking pests only", "Changing crops only"], "Use of approved pesticides or chemicals to control pests or diseases", "Chemical control uses approved chemicals safely to reduce pests or diseases.", "medium"),
    mcq("l3-q10", l3, "What is biological control?", ["Using natural enemies to control pests", "Burning all plants", "Using only slogans", "Drawing diagrams"], "Using natural enemies to control pests", "Biological control uses predators, parasites, or other natural enemies.", "medium"),
    mcq("l3-q11", l3, "Which is a cultural control method?", ["Crop rotation", "Overuse of pesticides", "Illegal hunting", "Embryo implantation"], "Crop rotation", "Crop rotation is a cultural practice that can reduce pest and disease build-up.", "medium"),
    mcq("l3-q12", l3, "Which is mechanical or physical control?", ["Hand-picking pests", "Using a placenta", "Building wildlife corridors", "Making conservation slogans"], "Hand-picking pests", "Mechanical control physically removes or blocks pests.", "medium"),
    mcq("l3-q13", l3, "What does quarantine help prevent?", ["Entry and spread of pests and diseases", "Egg laying", "Tree planting", "Milk production"], "Entry and spread of pests and diseases", "Quarantine stops infected materials or organisms from spreading pests and diseases.", "medium"),
    mcq("l3-q14", l3, "What are resistant varieties?", ["Plant varieties that can resist pests or diseases", "Animals in game reserves", "Water-saving taps", "Female reproductive organs"], "Plant varieties that can resist pests or diseases", "Resistant varieties reduce damage from specific pests or diseases.", "hard"),
    mcq("l3-q15", l3, "Which is a benefit of pest and disease control?", ["Increased crop yield", "More crop loss", "More pollution always", "No food quality"], "Increased crop yield", "Control methods can protect crops and increase yield.", "easy"),
    mcq("l3-q16", l3, "Which is a possible drawback of chemical control?", ["Environmental pollution", "Guaranteed zero resistance", "No cost", "No harm to any organism"], "Environmental pollution", "Chemicals can pollute the environment if misused.", "hard"),
    mcq("l3-q17", l3, "What is integrated pest management?", ["Combining different control methods wisely", "Using only one chemical always", "Ignoring pest levels", "Stopping all farming"], "Combining different control methods wisely", "Integrated management combines methods to improve control and reduce drawbacks.", "hard"),
    mcq("l3-q18", l3, "Which pest type includes snails and slugs?", ["Mollusk pests", "Rodent pests", "Bird pests", "Microbial pests"], "Mollusk pests", "Snails and slugs are mollusk pests.", "medium"),
    mcq("l3-q19", l3, "Which pest type includes striga and water hyacinth?", ["Weed pests", "Mite pests", "Rodent pests", "Bird pests"], "Weed pests", "Striga and water hyacinth are weed pests.", "medium"),
    mcq("l3-q20", l3, "Why should control methods be compared before use?", ["Each method has benefits and drawbacks", "All methods are perfect", "Control methods never cost money", "Pests cannot develop resistance"], "Each method has benefits and drawbacks", "A good choice considers effectiveness, cost, safety, and environmental impact.", "hard")
  ],

  [l4]: [
    mcq("l4-q1", l4, "What is reproduction?", ["The process by which organisms produce offspring", "The protection of water", "The control of pests", "The recycling of waste"], "The process by which organisms produce offspring", "Reproduction allows organisms to produce new individuals of their own kind.", "easy"),
    mcq("l4-q2", l4, "What type of reproduction occurs in birds and mammals in this lesson?", ["Sexual reproduction", "Binary fission only", "Budding only", "Fragmentation only"], "Sexual reproduction", "Birds and mammals reproduce sexually using male and female reproductive cells.", "easy"),
    mcq("l4-q3", l4, "What does internal fertilization mean?", ["Fusion of gametes inside the female body", "Fusion of gametes in soil", "Fertilization outside all bodies", "Fertilization in a leaf"], "Fusion of gametes inside the female body", "Birds and mammals have internal fertilization.", "medium"),
    mcq("l4-q4", l4, "Birds are described as oviparous because they", ["Lay eggs", "Give birth to live young only", "Feed young with milk", "Have a placenta"], "Lay eggs", "Oviparous animals lay eggs.", "easy"),
    mcq("l4-q5", l4, "Most mammals are viviparous because they", ["Give birth to live young", "Lay hard-shelled eggs", "Have feathers", "Use yolk only for embryo nutrition"], "Give birth to live young", "Viviparous animals give birth to live young.", "easy"),
    mcq("l4-q6", l4, "Where does the bird embryo develop?", ["Inside an egg outside the mother's body", "Inside the uterus", "Inside the placenta", "Inside the mammary gland"], "Inside an egg outside the mother's body", "Bird embryos develop in eggs after the eggs are laid.", "medium"),
    mcq("l4-q7", l4, "Where does the mammalian embryo usually develop?", ["Uterus", "Cloaca", "Magnum", "Eggshell"], "Uterus", "The uterus supports development of the mammalian embryo.", "medium"),
    mcq("l4-q8", l4, "What nourishes the bird embryo inside the egg?", ["Yolk", "Placenta", "Mammary gland", "Cowper's gland"], "Yolk", "The yolk supplies food for the developing bird embryo.", "medium"),
    mcq("l4-q9", l4, "What nourishes the mammalian embryo in the uterus?", ["Placenta", "Eggshell", "Yolk only", "Feathers"], "Placenta", "The placenta helps transfer nutrients and oxygen from mother to embryo.", "medium"),
    mcq("l4-q10", l4, "Which organ produces sperm in male mammals?", ["Testes", "Ovary", "Uterus", "Oviduct"], "Testes", "Testes produce male gametes called sperm.", "easy"),
    mcq("l4-q11", l4, "Which organ produces eggs or ova in female mammals?", ["Ovaries", "Testes", "Vas deferens", "Prostate gland"], "Ovaries", "Ovaries produce female gametes called ova.", "easy"),
    mcq("l4-q12", l4, "Which male mammal structure stores sperm temporarily?", ["Epididymis", "Uterus", "Ovary", "Vagina"], "Epididymis", "The epididymis stores sperm after they are produced in the testes.", "hard"),
    mcq("l4-q13", l4, "Which tube transports sperm in male mammals?", ["Vas deferens", "Fallopian tube", "Oviduct", "Cervix"], "Vas deferens", "The vas deferens carries sperm from the epididymis toward the urethra.", "hard"),
    mcq("l4-q14", l4, "Which organ receives the penis during mating in female mammals?", ["Vagina", "Ovary", "Testis", "Seminal vesicle"], "Vagina", "The vagina receives sperm during mating and also serves as a birth canal.", "medium"),
    mcq("l4-q15", l4, "Which female mammal tube is linked with fertilization?", ["Fallopian tube", "Urethra", "Vas deferens", "Seminal vesicle"], "Fallopian tube", "In mammals, fertilization usually occurs in the fallopian tube.", "hard"),
    mcq("l4-q16", l4, "Which female bird organ produces the ovum?", ["Ovary", "Cloaca", "Magnum", "Uterus or shell gland"], "Ovary", "The ovary produces ova in female birds.", "medium"),
    mcq("l4-q17", l4, "Which bird structure is common to digestive, urinary, and reproductive exits?", ["Cloaca", "Placenta", "Mammary gland", "Cervix"], "Cloaca", "The cloaca is a common chamber/opening in birds.", "hard"),
    mcq("l4-q18", l4, "Which bird part adds the shell around the egg?", ["Uterus or shell gland", "Testis", "Vas deferens", "Ovary"], "Uterus or shell gland", "The shell gland forms the hard shell around the egg.", "hard"),
    mcq("l4-q19", l4, "Which feature is common to reproduction in birds and mammals?", ["Internal fertilization", "Milk feeding in both groups", "Egg laying in both groups only", "Placenta in both groups"], "Internal fertilization", "Both birds and mammals have internal fertilization.", "hard"),
    mcq("l4-q20", l4, "Which is a major difference between birds and mammals?", ["Birds lay eggs while most mammals give birth to live young", "Both use placenta in the same way", "Both have feathers", "Mammals lay shelled eggs in this lesson"], "Birds lay eggs while most mammals give birth to live young", "Birds are oviparous, while most mammals are viviparous.", "hard")
  ],

  [l6]: [
    mcq("l6-q1", l6, "What is fertilization?", ["Fusion of sperm and egg to form a zygote", "Planting trees", "Removing pests by hand", "Protecting forests"], "Fusion of sperm and egg to form a zygote", "Fertilization joins male and female gametes to begin development.", "easy"),
    mcq("l6-q2", l6, "What is formed immediately after fertilization?", ["Zygote", "Adult", "Seedling", "Conservation slogan"], "Zygote", "The zygote is the first cell formed after sperm and egg fuse.", "easy"),
    mcq("l6-q3", l6, "Where does fertilization occur in birds according to the lesson?", ["Infundibulum of the oviduct", "Mammary gland", "Placenta", "Cervix"], "Infundibulum of the oviduct", "In birds, fertilization occurs in the infundibulum before other egg layers are added.", "medium"),
    mcq("l6-q4", l6, "Where does fertilization usually occur in mammals?", ["Fallopian tube", "Eggshell", "Cloaca", "Magnum"], "Fallopian tube", "In mammals, sperm and egg usually fuse in the fallopian tube.", "medium"),
    mcq("l6-q5", l6, "What is embryonic development?", ["Early growth and development of a young organism", "Cutting trees", "Writing slogans", "Storing rainwater"], "Early growth and development of a young organism", "Embryonic development is the early stage of growth after fertilization.", "easy"),
    mcq("l6-q6", l6, "Bird embryos develop mainly", ["Inside eggs outside the mother's body", "Inside the uterus with a placenta", "Inside mammary glands", "Inside the testes"], "Inside eggs outside the mother's body", "Bird embryos develop in eggs laid outside the mother.", "medium"),
    mcq("l6-q7", l6, "Mammalian embryos are supported by", ["Placenta and umbilical cord", "Eggshell and albumen only", "Feathers", "Cloaca only"], "Placenta and umbilical cord", "The placenta and umbilical cord help nourish the developing mammalian embryo.", "medium"),
    mcq("l6-q8", l6, "What does implantation mean in mammals?", ["Attachment of the developing embryo to the uterine wall", "Laying an egg", "Formation of a shell", "Removal of pests"], "Attachment of the developing embryo to the uterine wall", "Implantation allows the embryo to receive support from the uterus.", "hard"),
    mcq("l6-q9", l6, "Which stage comes before embryo development?", ["Zygote formation", "Adult parental care", "Milk feeding", "Hatching"], "Zygote formation", "The zygote forms first and then divides to begin embryo development.", "medium"),
    mcq("l6-q10", l6, "What is parental care?", ["Care given by parents to help offspring survive", "Careless use of resources", "Disease spread", "Soil erosion"], "Care given by parents to help offspring survive", "Parental care includes protection, feeding, warmth, and guidance.", "easy"),
    mcq("l6-q11", l6, "Which is an example of parental care in birds?", ["Incubating eggs", "Producing milk from mammary glands", "Using a placenta", "Contour ploughing"], "Incubating eggs", "Bird parents often incubate eggs to keep embryos warm.", "medium"),
    mcq("l6-q12", l6, "Which is an example of parental care in mammals?", ["Feeding young with milk", "Laying shelled eggs", "Adding albumen to eggs", "Using only yolk"], "Feeding young with milk", "Mammals feed their young with milk from mammary glands.", "medium"),
    mcq("l6-q13", l6, "What does a labelled drawing require?", ["A diagram with correct names attached to parts", "A blank picture only", "A slogan only", "A list of pests only"], "A diagram with correct names attached to parts", "A labelled drawing shows structures and names them correctly.", "easy"),
    mcq("l6-q14", l6, "What is the role of albumen in a bird egg?", ["It supplies water and protein and cushions the embryo", "It produces sperm", "It acts as a placenta", "It becomes a mammary gland"], "It supplies water and protein and cushions the embryo", "Albumen helps nourish and protect the developing bird embryo.", "hard"),
    mcq("l6-q15", l6, "What is the role of the eggshell?", ["Protection while allowing gas exchange through pores", "Producing ova", "Feeding young with milk", "Carrying sperm"], "Protection while allowing gas exchange through pores", "The shell protects the embryo and allows gases to pass through tiny pores.", "hard"),
    mcq("l6-q16", l6, "Which structure connects a mammalian embryo to the placenta?", ["Umbilical cord", "Cloaca", "Eggshell", "Magnum"], "Umbilical cord", "The umbilical cord links the embryo to the placenta for exchange of materials.", "hard"),
    mcq("l6-q17", l6, "Which sequence is correct for early mammalian development?", ["Zygote, embryo, fetus", "Fetus, zygote, embryo", "Adult, egg, zygote", "Slogan, embryo, fetus"], "Zygote, embryo, fetus", "Development begins with the zygote, then embryo, then fetus.", "hard"),
    mcq("l6-q18", l6, "What happens during incubation in birds?", ["Eggs are kept warm for embryo development", "Young are fed with milk", "The placenta forms", "The uterus receives an embryo"], "Eggs are kept warm for embryo development", "Incubation provides warmth needed by the developing bird embryo.", "medium"),
    mcq("l6-q19", l6, "Which topic belongs to Lesson Six?", ["Fertilization, embryonic development, and parental care", "Forest slogans only", "Water conservation only", "Types of weed pests only"], "Fertilization, embryonic development, and parental care", "Lesson Six covers reproductive drawings, fertilization, development, and parental care.", "medium"),
    mcq("l6-q20", l6, "Which comparison is correct?", ["Bird embryos use yolk; mammal embryos receive support through placenta", "Both groups use placenta only", "Both groups develop only in shells", "Mammals use yolk as their only support"], "Bird embryos use yolk; mammal embryos receive support through placenta", "Bird embryos develop in eggs with yolk, while mammalian embryos develop in the uterus with placental support.", "hard")
  ]
};

